Feature #10 -  Social buttons and read time
CodemateLtd/codemate-blog pull request #13
Opened 2018-03-13 12:04 UTC by kennyhei

Added social sharing buttons using Fontawesome icons and Sass - #10

2018-03-13 12:26 UTC, roughike commented
@kennyhei I edited your description a little.

If you say `Fixes #123`, the corresponding issue will automatically get closed when the pull request gets merged. :)

2018-03-13 12:36 UTC, ragmha requested changes
Good work! 🎉 

Few changes required:

1)  Move FontAwesome inline-style to SocialLinks.module.scss
https://github.com/CodemateLtd/codemate-blog/pull/13/files#diff-f7e02c369b70c795cab9fdae3d761de4

2) Move the timeToRead outside render method, so its a method of the BlogPostTemplate https://github.com/CodemateLtd/codemate-blog/pull/13/files#diff-b334c7299860c69226f3d8a8f4a36c1f

3) Is it possible to move all the blog-post inline-styling to an index.scss or should I work on it? https://github.com/CodemateLtd/codemate-blog/pull/13/files#diff-b334c7299860c69226f3d8a8f4a36c1f

4) Could you make the Sharing button be something like this using flex-box instead of table, https://www.behance.net/gallery/9665081/Share-Button

2018-03-13 12:52 UTC, kennyhei commented
Sure, I'll work on it

2018-03-13 13:36 UTC, roughike commented on src/components/share/links/FacebookLink.js
> +    shareSite = encodeURIComponent(`https://${host}:${port}${slug}`),
The Netlify builds broke due to the following reason: 

```
GraphQL Error: There was an error while compiling your site's GraphQL queries.
Invariant Violation: GraphQLParser: Unknown field `host` on type `Site`. Source: document `BlogPostBySlug` file: `GraphQL request`.
```

I would bet that these will also break "real" sites (think when this blog gets published) as well, although locally on `localhost:4000` they will work fine.

2018-03-13 13:41 UTC, roughike requested changes
I think the latest changes broke the build for deployed sites. In other words, it works locally, but will not work when trying to actually publish the blog.

2018-03-13 13:41 UTC, roughike commented on src/components/share/links/FacebookLink.js
> +    shareSite = encodeURIComponent(`https://${host}:${port}${slug}`),
The Netlify builds broke due to the following reason: 

```
GraphQL Error: There was an error while compiling your site's GraphQL queries.
Invariant Violation: GraphQLParser: Unknown field `host` on type `Site`. Source: document `BlogPostBySlug` file: `GraphQL request`.
```

I would bet that these will also break "real" sites (think when this blog gets published) as well, although locally on `localhost:4000` they will work fine.

2018-03-13 13:41 UTC, roughike commented on src/components/share/links/LinkedinLink.js
> +    shareSite = encodeURIComponent(`https://${host}:${port}${slug}`),
See the very first comment above.

2018-03-13 13:41 UTC, roughike commented on src/components/share/links/MailLink.js
> +    shareSite = encodeURIComponent(`https://${host}:${port}${slug}`),
See the very first comment above.

2018-03-13 13:41 UTC, roughike commented on src/components/share/links/TwitterLink.js
> +    shareSite = encodeURIComponent(`https://${host}:${port}${slug}`),
See the very first comment above.

2018-03-13 13:54 UTC, ragmha reviewed
Regarding the Social Links there seems to be a lot of repeated code.A good reference should be this https://github.com/tfiechowski/react-social-share-buttons

2018-03-13 13:54 UTC, ragmha commented on src/components/share/links/ShareLink.js
> +          style={{ textShadow: '0 1px 0 rgba(0, 0, 0, 0.1)' }}
Move inline styles to ../SocialLinks.module.scss

2018-03-13 13:54 UTC, ragmha commented on src/templates/blog-post.js
> +    const timeToRead = () => {
functions shouldn't be a part of render method, you can it a method of BlogPlostTemplate class. 

More info: https://stackoverflow.com/questions/24718709/reactjs-does-render-get-called-any-time-setstate-is-called?answertab=votes#tab-top

2018-03-13 13:54 UTC, ragmha commented on src/components/share/SocialLinks.module.scss
> +.shareList {
Would be a good idea to use Flexbox layout.

A clone of this: https://www.behance.net/gallery/9665081/Share-Button would be nice, but the design will be changed in future 

More info: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2018-03-14 21:44 UTC, roughike approved these changes

2018-03-14 21:45 UTC, roughike commented
The build is working again and the buttons look good! 💯

2018-03-15 10:48 UTC, ragmha requested changes
![screen shot 2018-03-15 at 12 46 28](https://user-images.githubusercontent.com/6115991/37458987-689f31ce-284f-11e8-93bd-55999417a5f5.png)

- [ ] Make Button Size similar to Quora site:
- [ ]  Regarding spacing, you can use flexbox  for justify-content: space-between
- [ ]  Add media queries so that buttons are sized properly across different screen size 

Remaining looks great! 💯

2018-03-15 12:18 UTC, ragmha approved these changes

2018-03-15 12:20 UTC, merged